### ISSUE TITLE
Observable.fromCoroutine feeds 1 observer at a time

### ISSUE THREAD

**Issue by titouanc** [bjornbytes/RxLua#15]
I don't know if this is a bug or an actual implementation requirement. When an observable is created from a coroutine, the yielded value is fed to only 1 observer.

From my point of view, it seems that the 2 following snippets should result in all elements outputed twice

### Using Observable.fromRange
```lua
local stream = Rx.Observable.fromRange(0, 100)
stream:dump("Stream 1")
stream:dump("Stream 2")
```

### Using Observable.fromCoroutine
```lua
local scheduler = Rx.CooperativeScheduler.create()

function myRange()
    local r = 0
    while r < 100 do
        coroutine.yield(r)
        r = 1 + r
    end
    return r
end

local stream = Rx.Observable.fromCoroutine(myRange, scheduler)
stream:dump("Stream 1")
stream:dump("Stream 2")

repeat scheduler:update() until scheduler:isEmpty()
```

The first one behave as expected (all elements outputted twice), but in the second case, I see the following output (output 1 and 2 are alternating):

```
Stream 2 onNext: 0
Stream 1 onNext: 1
Stream 2 onNext: 2
Stream 1 onNext: 3
Stream 2 onNext: 4
Stream 1 onNext: 5
Stream 2 onNext: 6
Stream 1 onNext: 7
Stream 2 onNext: 8
Stream 1 onNext: 9
...
```

**Comment by bjornbytes** [comment]
Yes, this is a bug, thanks for finding it.  The Observable was using a shared coroutine, so any subscribed Observers were sharing values yielded by the coroutine.  It's possible to work around this using a Subject:

```lua
local stream = Rx.Observable.fromCoroutine(myRange, scheduler)
local subject = Rx.Subject.create()

stream:subscribe(subject)

subject:dump("Stream 1")
subject:dump("Stream 2")
```

However, I've gone ahead and changed things so each Observer will get a unique coroutine if a function is passed to `Observable.fromCoroutine`.

Note that the issue will still come up if a coroutine is used instead of a function because coroutines aren't stateless -- in those cases a Subject is still necessary.  I've clarified this in the documentation.
