### ISSUE TITLE
Subject:map returns Observable

### ISSUE THREAD

**Issue by MelomanCool** [bjornbytes/RxLua#17]
Not sure if this is a bug, but it was unexpected for me.

**Example**:
```lua
local subject = Rx.Subject.create()
local mappedSubject = subject:map(
  function(x)
    return x
  end
)

print(tostring(subject))
print(tostring(mappedSubject))
```

**Output**:
```
Subject
Observable
```

**Comment by bjornbytes** [comment]
Yeah, this is intentional but a little weird right now.  Confusion aside, can you elaborate on whether or not this causes any functional problems for you?

**Comment by MelomanCool** [comment]
Well, I still can send messages to `subject` and all subscribers of `mappedSubject` receive them.
But I think you should note that behavior in the documentation.

**Comment by greatwolf** [comment]
Do any of the other Rx frameworks for other languages, work like this? From what I can tell, operators always returns a new stream(aka. observable) so calling `on*` would be an interface mismatch since it's not observers.

**Comment by bjornbytes** [comment]
RxJS 5 lets you do this, I think it stores the Observable operators separately and then applies them later rather than returning a new Observable each time an operator is applied.  RxJS 4 works this way though.

**Comment by bonzini** [comment]
This is actually really useful when interfacing with external event sources. First, you create a `Subject` for internal use only, and call `subject:onNext` whenever the external event source reports that something has happened. This way you can forget completely about managing subscriptions and returning unsubscribe functions. However, when you're asked for an observable, instead of returning the subject you make a read-only version using `subject:map(identity)`.
